AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/ModuleLength:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Exclude:
    - orchestrator/rake/lib/chef-provisioner.rb
Naming/HeredocDelimiterNaming:
  Enabled: false
Security/MarshalLoad:
  Exclude:
    - lib/job_live_output.rb 
    - test/**/*
